import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import { loginTwitter, logoutTwitter } from "../firebase/auth";
import { useUser } from "../hooks/user";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [inputValue, setInputValue] = useState("");

  const user = useUser();

  const login = async () => {
    await loginTwitter();
  };

  const logout = async () => {
    await logoutTwitter();
  };

  const post = async () => {
    if (!user || inputValue === "") return;

    const url = "/api/post";
    const data = {
      idToken: await user.getIdToken(),
      status: inputValue,
    };

    const result = await axios.post(url, data).catch((e) => e);
    console.log(result);

    setInputValue("");
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user ? (
          <div>
            <button onClick={() => logout()}>logout</button>
            <div>
              <input type="text" value={inputValue} onChange={handleChange} />
            </div>
            <div>
              <button onClick={() => post()}>tweet</button>
            </div>
          </div>
        ) : (
          <div>
            <button onClick={() => login()}>login</button>
          </div>
        )}
      </main>
    </div>
  );
}
