import { User } from "@firebase/auth";
import axios from "axios";
import Head from "next/head";
import { useState } from "react";
import { loginTwitter, logoutTwitter } from "../firebase/auth";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [user, setUser] = useState<User | null>(null);
  const [inputValue, setInputValue] = useState("");
  const [isAuth, setIsAuth] = useState(false);

  const login = async () => {
    const user = await loginTwitter();

    if (user == null) return;
    setUser(user);
    setIsAuth(true);
  };

  const logout = async () => {
    await logoutTwitter();
    setUser(null);
    setIsAuth(false);
  };

  const post = async () => {
    if (!user) return;

    const url = "/api/post";
    const data = {
      idToken: user.getIdToken(),
      status: inputValue,
    };

    const result = await axios.post(url, data).catch((e) => e);
    console.log(result);

    setInputValue("");
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputValue(e.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isAuth ? (
          <div>
            <button onClick={() => logout()}>logout</button>
            <div>
              <input type="text" value={inputValue} onChange={handleChange} />
            </div>
            <div>
              <button onClick={() => post()}>tweet</button>
            </div>
          </div>
        ) : (
          <div>
            <button onClick={() => login()}>login</button>
          </div>
        )}
      </main>
    </div>
  );
}
