import Head from "next/head";
import TweetForm from "../components/TweetForm";
import { loginTwitter, logoutTwitter } from "../firebase/auth";
import { useUser } from "../hooks/user";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const user = useUser();

  const login = async () => {
    await loginTwitter();
  };

  const logout = async () => {
    await logoutTwitter();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user ? (
          <div>
            <TweetForm user={user} />
            <button onClick={() => logout()}>logout</button>
          </div>
        ) : (
          <div>
            <button onClick={() => login()}>login</button>
          </div>
        )}
      </main>
    </div>
  );
}
